### ISSUE TITLE
Problems with AudioSegment.from_mp3

### ISSUE THREAD

**Issue by sopekmir** [jiaaro/pydub#62]
Hello James,
I have Python2.7 (Win) and got latest pydub.
When trying to open mp3 file using:
song = AudioSegment.from_mp3("b.mp3")
(while double checking with os.listdir that I do have the file in current folder), 
I'm getting:

> > > song = AudioSegment.from_mp3("b.mp3")

Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    song = AudioSegment.from_mp3("b.mp3")
  File "build\bdist.win32\egg\pydub\audio_segment.py", line 318, in from_mp3
    return cls.from_file(file, 'mp3')
  File "build\bdist.win32\egg\pydub\audio_segment.py", line 302, in from_file
    retcode = subprocess.call(convertion_command, stderr=open(os.devnull))
  File "C:\Python27\lib\subprocess.py", line 486, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 672, in **init**
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 882, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

What's the problem?
Additionaly while I do first time: from pydub import AudioSegment 
I'm getting:
Warning (from warnings module):
  File "C:\Python27\lib\site-packages\pydub-0.9.2-py2.7.egg\pydub\utils.py", line 122
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work

The repeated import goes without warning.

So - what it can be that I can't open plain mp3 file ?

my email is: sopekmir@makolab.pl

**Comment by mosynaq** [comment]
I assign the path to 'ffmpeg.exe' to both AudioSegment.converter and AudioSegment.ffmpeg but i receive the same error:
`C:\Python34\python.exe "D:/path/to/project/SplitWavFiles.py"
C:\Python34\lib\site-packages\pydub\utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)`

**Comment by jiaaro** [comment]
@mosynaq That warning indicates that ffmpeg wasn't found in the path. If you then assign `AudioSegment.converter` to the correct value, you should be able to ignore the warning and continue normally.

**Comment by WiliTest** [comment]
I could not get rid of the error, but it's working with it.

**Comment by jiaaro** [comment]
@WiliTest yeah, it's a runtime warning (not error) - if you know it won't cause a problem in your specific  application and configuration it's safe to ignore. It's just there to inform users that the auto detection was not successful so they will need to set converter manually.

You can suppress runtime warnings in the python interpreter (in a shipping product for instance) by running your program with [the -W option](https://docs.python.org/2/using/cmdline.html#cmdoption-W) like `python -W ignore my_script_using_pydub.py`

You can also put ffmpeg.exe in the directory your program runs in since that is one place pydub looks for it.

**Comment by WiliTest** [comment]
thanks for your reply Jiaaro, I understand. And thanks a lot for your work, the module is awesome!

**Comment by nikesh0822** [comment]
@WiliTest, Hello. I have the following error. How could I resolve this?

`I'm listening
Found audio
Google Speech Recognition thinks you said hello mirror
Traceback (most recent call last):
  File "bot.py", line 254, in <module>
    bot.start()
  File "bot.py", line 45, in start
    self.__acknowledge_action()
  File "bot.py", line 143, in __acknowledge_action
    self.__text_action(self.nlg.acknowledge())
  File "bot.py", line 154, in __text_action
    self.speech.synthesize_text(text)
  File "/home/pi/AI-Smart-Mirror/speech.py", line 55, in synthesize_text
    song = AudioSegment.from_mp3("tmp.mp3")
  File "/usr/local/lib/python2.7/dist-packages/pydub/audio_segment.py", line 514, in from_mp3
    return cls.from_file(file, 'mp3')
  File "/usr/local/lib/python2.7/dist-packages/pydub/audio_segment.py", line 497, in from_file
    p = subprocess.Popen(conversion_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
`

**Comment by jiaaro** [comment]
@nikesh0822 That stack trace is very likely because ffmpeg is not installed or can't be found. Have you tried manually setting the converter as suggested earlier in this thread?

**Comment by nikesh0822** [comment]
hey @jiaaro , I did install ffmpeg but may be I went wrong somewhere while manually setting the converter. But thanks for the help, I fixed it. I had a line
`song = song = AudioSegment.from_mp3("tmp.mp3")`  as mentioned in the above and replaced it with
`import subprocess
subprocess.Popen(['mpg123','-q', 'tmp.mp3']).wait()`
and that worked well.
Thanks anyways @jiaaro

**Comment by nikesh0822** [comment]
hey @jiaaro , I did install ffmpeg but may be I went wrong somewhere while manually setting the converter. But thanks for the help, I fixed it. I had a line
`song = song = AudioSegment.from_mp3("tmp.mp3")`  as mentioned in the above and replaced it with
`import subprocess`
`subprocess.Popen(['mpg123','-q', 'tmp.mp3']).wait()`
and that worked well.
Thanks anyways @jiaaro

**Comment by ahwangyuwei** [comment]
# libav
apt-get install libav-tools libavcodec-extra-53

####    OR    #####

# ffmpeg
apt-get install ffmpeg libavcodec-extra-53

**Comment by lgming** [comment]
hey @jiaaro ,i set the path like this. But i still not work on centos:
AudioSegment.converter ="/monchickey/ffmpeg/bin/ffmpeg"
sound = AudioSegment.from_file(wav_path + "\\" + name, format="wav") 
i have installed ffmpeg on centos.

**Comment by jiaaro** [comment]
@lgming In your case I suspect it's the second line: `wav_path + "\" + name`

Shouldn't the slash be a forward slash? like `wav_path + "/" + name` ?

**Comment by lgming** [comment]
@jiaaro many thanks, I make a low-level error. And thanks a lot for your work, it is awesome!

**Comment by joshuakery** [comment]
I tried that, but it still doesn't work and there's no change to the error and warnings.

**Comment by MarkoGill** [comment]
@joshuakery I ran into that issue recently and previously wasn't experiencing issues. I had to add the directory containing ffprobe to PATH. Hope this helps.

**Comment by wewark** [comment]
I am having the same issue.
I have downloaded `ffmpeg` and added it path and its warnings are gone, but it still gives
`FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by kartiksonu** [comment]
> # libav
> 
> apt-get install libav-tools libavcodec-extra-53
> #### OR
> # ffmpeg
> 
> apt-get install ffmpeg libavcodec-extra-53

this worked for me

**Comment by agarwalkaushal** [comment]
> I am having the same issue.
> I have downloaded `ffmpeg` and added it path and its warnings are gone, but it still gives
> `FileNotFoundError: [WinError 2] The system cannot find the file specified`

Same error for Windows! Please help.

**Comment by elahimanesh** [comment]
> > I am having the same issue.
> > I have downloaded `ffmpeg` and added it path and its warnings are gone, but it still gives
> > `FileNotFoundError: [WinError 2] The system cannot find the file specified`
> 
> Same error for Windows! Please help.

you need to this:
1- Download and extract libav from Windows binaries provided here. (http://builds.libav.org/windows/)
2- Add the libav /bin folder to your PATH envvar
3- pip install pydub

**Comment by juihsuanlee** [comment]
@elahimanesh 
hi I have done the steps above but I still have the same error message.
please hlp me thank you

**Comment by sedthh** [comment]
same here, tried to install everything mentioned here and still got an error

**Comment by Extalionos** [comment]
I have windows.
If i use this, i have error
```
AudioSegment.converter = ffmpeg_catalog+'ffmpeg.exe'
AudioSegment.ffmpeg = ffmpeg_catalog+'ffmpeg.exe'
AudioSegment.ffprobe = ffmpeg_catalog+'ffprobe.exe'

```
But when i add "C:\ffmpeg\bin\" to PATH and restart os it works.
And you must to remove lines above.

**Comment by Venkat-18** [comment]
I am having the same error while running the python via ATOM editor using plugins
C:\Python27\lib\site-packages\pydub\utils.py:193: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)

When i run it in the Command Prompt It works.
If anyone having the same issue while running the python via any editors
Try running the file via command prompt.

**Comment by anshgupta1234** [comment]
I've tried fixing this problem for 2 hours and I'm almost ready to quit. I've done everything this thread has asked and more.

I added ffmpegg to PATH.

This is my code:

`AudioSegment.converter = r"C:\Program Files\FFmpeg\bin"
`

**Comment by warwarra** [comment]
Hi, im trying to run:
`sample = AudioSegment.from_file(song_dir + "/" + filename, format= "mp3")`

But it returns:
`pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1`

`Output from ffmpeg/avlib:`

`b"avconv version 12.3, Copyright (c) 2000-2018 the Libav developers`
`  built on Jan 22 2019 21:47:08 with Apple LLVM version 10.0.0 (clang-1000.11.45.5)`
`[mp3 @ 0x7fcaea008600] Header missing\n[mp3 @ 0x7fcaea002200] Could not find codec parameters (Audio: mp3`
`      0 channels, s16p)`
`[mp3 @ 0x7fcaea002200] Estimating duration from bitrate, this may be inaccurate`
`Input #0, mp3, from 'songs/.DS_Store':`
`  Duration: N/A, start: 0.000000, bitrate: N/A`
`    Stream #0:0: Audio: mp3`
`      0 channels, s16p`
`Output #0, wav, to 'pipe:':`
`Output file #0 does not contain any stream"`

What can I do to fix it?

**Comment by Sobiam1** [comment]
Hi

> 
> 
> I've tried fixing this problem for 2 hours and I'm almost ready to quit. I've done everything this thread has asked and more.
> 
> I added ffmpegg to PATH.
> 
> This is my code:
> 
> `AudioSegment.converter = r"C:\Program Files\FFmpeg\bin" `

Hi, 
Did you fix this issue with mmpeg ?

**Comment by derek-adair** [comment]
Ooof. This is a painful thread to sift through.... its **_FIVE_** years old and people still continue to revive it.  Let me tell you that pydub, ffmpeg and libav have all released MANY versions... 

A lot of you aren't even including most of the relevant information to help debug these.

1. What OS are you using?
2. What version of python?
3. What version of ffmpeg OR libav?
4. What version of pydub?

Without this info, contributors are basically taking shots in the dark as to why you are getting these errors.

this thread is a dumpster fire.  I'd suggest locking it w/ a link to the install instructions. @jiaaro you're a more patient maintainer than myself.

**Comment by derek-adair** [comment]
@warwarra - this is an entirely separate issue and deserves its own thread.

**Comment by amittal-tcd** [comment]
In anaconda you can resolve this issue by installing ffmpeg from conda-forge

conda install -c conda-forge ffmpeg

**Comment by CKanishka** [comment]
Thanks @amittal-tcd ,your solution did the job for me.

**Comment by nNasir** [comment]
Hi, 
Does the following work for ubuntu aswell?

AudioSegment.converter = r"C:\Program Files\FFmpeg\bin"

If not, what the way around can I use it in ubuntu? I don't have admin privileges to install ffmpeg

**Comment by ispassov** [comment]
For Windows:
- install ffmpeg
- set environment variable - > "_your ffmpeg installation directory_"\ffmpeg\bin
- log off OR restart windows

**Comment by harshittrehan** [comment]
Faced the same issue. Basically ffmpeg was missing. 
Install it, add it to PATH and most importantly, restart windows.

**Comment by andyyeyeye** [comment]
I have python running on windows 10, and when I try to move the FFmpeg folder to anywhere else than C:\\ and add a path to the file by doing
```
from pydub import AudioSegment
AudioSegment.converter = '/Program Files/FFmpeg/bin/ffmpeg.exe'
````
(yes I have tried 'AudioSegment.ffmpeg')

and try to open a mp3 file by 
```
song = AudioSegment.from_mp3("/Users/andyy/song.mp3")
```
It returns me an error that says 
`FileNotFoundError: [WinError 2] The system cannot find the file specified`

Can anyone tell me what the problem is?

The python version is 3.7

**Comment by Abuton** [comment]
You need to set path to ffmpeg.exe in your local drive (C) atleast that what I did and it worked. Also use AudioSegment.converter = r "path\to\ffmpeg.exe
Instead of AudioSegment ffmpeg don't use these use the first one. 
Also I tried this on windows 10 python 3.7 and it worked

**Comment by andyyeyeye** [comment]
It does work when I put ffmpeg.exe into `C:\\FFmpeg\bin` but I need to be able to put it somewhere else so I can package it with my exe-packaged-python-file and run it on any computer that does not have `ffmpeg` installed

**Comment by andyyeyeye** [comment]
Mabye I need to add a `PATH` to windows pointing in that direction?

**Comment by Tensorflow-Ranger** [comment]
I faced the same issue even after adding ffmpeg to PATH. I moved ffmpeg.exe, ffplay.exe, ffprobe.exe from `C:\ffmpeg\bin` to the directory where the code is running and it worked.

**Comment by kunakl07** [comment]
I am getting this issue while using it on docker, could anyone please help

/usr/local/lib/python3.6/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
The mean of the call duration is 1.9663194445714285
Traceback (most recent call last):
  File "./preprocess.py", line 447, in <module>
    args.grayscale
  File "./preprocess.py", line 344, in main
    call_annotations
  File "./preprocess.py", line 115, in extract_audio
    sound = AudioSegment.from_file(audio_file)
  File "/usr/local/lib/python3.6/site-packages/pydub/audio_segment.py", line 622, in from_file
    file, close_file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
  File "/usr/local/lib/python3.6/site-packages/pydub/utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)

**Comment by hanzigs** [comment]
I have same issue,
![image](https://user-images.githubusercontent.com/30790120/91922917-7cf75680-ed12-11ea-9475-0e29be563355.png)

Whether pydub package got withdrawn?

**Comment by paqstd** [comment]
I have a similar problem. It's weird that it wasn't added to the readme ...

**Comment by Vladislav2018** [comment]
Hi everybody. 
I use Python 3.8 and Windows 10.
When I try: 

`raw_sound = pydub.AudioSegment.from_mp3(file=track_path)`
I get this: 
```
D:\prog\datascience\anaconda\lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "D:/testtask2/test_task/testtask/get_mffc.py", line 165, in <module>
    slice_all_in_a_dir('May 27 2020 LNC/Hydrophone 1/raw_records')
  File "D:/testtask2/test_task/testtask/get_mffc.py", line 70, in slice_all_in_a_dir
    slice_samples(track_path= [file],
  File "D:/testtask2/test_task/testtask/get_mffc.py", line 48, in slice_samples
    raw_sound = pydub.AudioSegment.from_mp3(file=track_path[0])
  File "D:\prog\datascience\anaconda\lib\site-packages\pydub\audio_segment.py", line 738, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "D:\prog\datascience\anaconda\lib\site-packages\pydub\audio_segment.py", line 685, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "D:\prog\datascience\anaconda\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "D:\prog\datascience\anaconda\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\prog\datascience\anaconda\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Process finished with exit code 1
```
I tried:

1. `pip install ffmeg`
2. Download ffmpeg separately and set the path globally in file:

```
PATH_TO_FFMPEG = r'D:\\prog\\ffmpeg-win-2.2.2\\ffmpeg.exe'
pydub.AudioSegment.converter = PATH_TO_FFMPEG
```

Nothing has changed, I get the same Traceback.

Path to the track I give as atumatically generated absolute path. I'm sure this path is correct.

**Comment by RussianDraco** [comment]
I am having an issue with this as well but I have an addition, instead of doing AudioSegment.from_file(file_name) try doing AudioSegment.from_file(file_path), it sometimes works

**Comment by pzarzycki** [comment]
Same. Cant load .mp3 on Windows. I tried assigning     AudioSegment.ffmpeg,  AudioSegment.converter and even copying ffmepeg to C:/FFmpeg/bin as others suggested. Nothing works.

**Comment by lev007-ops** [comment]
Hey @jiaaro, i have this code: 
```python
import pydub
pydub.AudioSegment.converter = r"ffmpeg.exe"
sound = pydub.AudioSegment.from_mp3(file_src)
```
But on startup I get the error: 
```
Traceback (most recent call last):
  File "c:\Users\Дом\Desktop\Py\PY\e_garant_bot\audio_2_text.py", line 21, in <module>
    print(recognition('captcha_audio5.mp3', 'test.wav'))
  File "c:\Users\Дом\Desktop\Py\PY\e_garant_bot\audio_2_text.py", line 14, in recognition
    sound = pydub.AudioSegment.from_mp3(file_src)
  File "C:\Users\Дом\AppData\Local\Programs\Python\Python39\lib\site-packages\pydub\audio_segment.py", line 796, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "C:\Users\Дом\AppData\Local\Programs\Python\Python39\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "C:\Users\Дом\AppData\Local\Programs\Python\Python39\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Users\Дом\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Дом\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл
```
translation: `FileNotFoundError: [WinError 2] The specified file cannot be found`

what should I do? ffmpeg is located in the script folder.
Help me please

**Comment by grpnpraveen** [comment]
> @mosynaq That warning indicates that ffmpeg wasn't found in the path. If you then assign `AudioSegment.converter` to the correct value, you should be able to ignore the warning and continue normally.
> 
> If you are still getting a file not found error, it could be `S11.WAV` which is not being found.
> 
> Or if you just want to get rid of the runtime warning, you can add `D:\\path\\to\\ffmpeg\\` to your PATH so that it can be found automatically (which would make assigning `AudioSegment.converter` unnecessary)

Thanks, this worked !

**Comment by soumodeepsen** [comment]
Ref. https://github.com/soumodeepsen/mp3_to_wav/tree/main
I hope this piece of code by me helps you.

**Comment by AlkisPis** [comment]
> Have you installed ffmpeg? If so it's possible it's not in your search path. That warning means pydub was unable to locate the ffmpeg binary, which is used to handle format conversions.
> 
> You can set the ffmpeg path explicitly:
> 
> ```python
> import pydub
> 
> pydub.AudioSegment.converter = r"C:\\path\\to\\ffmpeg.exe"
> ```

Well, it doesn't work with me. 'AudioSegment.from_wav()' is OK. 'AudioSegment.from_mp3()'  refuses to work.

**Comment by AlkisPis** [comment]
In my case, Python 3.5, pydub 0.25.1, 'AudioSegment.from_mp3()' doesn;t work, whatever I do. 
The problem is not the path of ffmpeg. In fact, it has nothing to do woth 'ffmgeg'. I debugged   'pydub\audio_segment.py' and the problem lies in class method 'from_mp3(). More specifically:

    @classmethod`
    def from_mp3(cls, file, parameters=None):
       return cls.from_file(file, 'mp3', parameters=parameters)

'file' = "1.mp3" (in current path, even if given with full path), and 'parameters' = None
 Well, the 'from_file()' function raises **FileNotFoundError**.  Which is insane. Except of course, as it often happens, if this a false error or it refers to some other file that is not found, etc. Whatever is the case, what we have here is a huge bug.

**Comment by Oreldm** [comment]
> In my case, Python 3.5, pydub 0.25.1, 'AudioSegment.from_mp3()' doesn;t work, whatever I do. The problem is not the path of ffmpeg. In fact, it has nothing to do woth 'ffmgeg'. I debugged 'pydub\audio_segment.py' and the problem lies in class method 'from_mp3(). More specifically:
> 
> ```
> @classmethod`
> def from_mp3(cls, file, parameters=None):
>    return cls.from_file(file, 'mp3', parameters=parameters)
> ```
> 
> 'file' = "1.mp3" (in current path, even if given with full path), and 'parameters' = None Well, the 'from_file()' function raises **FileNotFoundError**. Which is insane. Except of course, as it often happens, if this a false error or it refers to some other file that is not found, etc. Whatever is the case, what we have here is a huge bug.

Same here. Confirmed on Windows 10.
I debugged it and I can see that we are calling on line 665 at audio_segment.py to `info = mediainfo_json(orig_file)`
This will essentially run `res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)` . In the command we will try to run ffprobe that might not be a valid command for every computer.

I don't think this is a good way to build the library (to rely on ffprobe command), and it should be changed. 
I'll try to find a solution for that.

At least for now- I will add a fix to send the right exception.

**Comment by jameswan** [comment]
I am on WIndows. This worked for me to remove this warning:
_C:\Users\James\anaconda3\envs\rich_transcription\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)_

Set your Environment Variables in Windows by adding this to Path:
**G:\ffmpeg-20171114-91a565e-win64-static\bin**

In your Python file, add this line:
**AudioSegment.converter = r"G:\\ffmpeg-20171114-91a565e-win64-static\\bin"**

**Comment by AlkisPis** [comment]
`AudioSegment.converter = r"G:\ffmpeg-20171114-91a565e-win64-static\bin"` **alone** does not work, simply because one must import the 'AudioSegment' module from pypub and `from pybub import AudioSegment` raises an error if 'ffmpeg\bin' folder is not in PATH. But then, if it is, one does not need  to add `AudioSegment.converter = ...` in the PY file. 🙂
